name: Build

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner'
        required: true
        type: string
        default: 'ubuntu-latest'

jobs:
  build:
    runs-on: ${{ github.event_name == 'workflow_dispatch' && inputs.runner || 'self-hosted' }}
    steps:
      - uses: actions/checkout@v5

      - name: Set ENV
        run: | 
          chmod +x *.sh
          echo "VERSION=$(date '+%Y.%m.%d')" >> $GITHUB_ENV
    
      - name: Build
        env:
            DEBIAN_FRONTEND: noninteractive
        run: |
          ./build.sh

      - name: Set
        run: |
          echo "KERNEL=$(find android/lineage/out/target/product/basic_x86_64_pc/kernel)" >> $GITHUB_ENV
          echo "SYSTEM=$(find android/lineage/out/target/product/basic_x86_64_pc/system.img)" >> $GITHUB_ENV
          echo "VENDOR=$(find android/lineage/out/target/product/basic_x86_64_pc/vendor.img)" >> $GITHUB_ENV
          echo "RAMDISK=$(find android/lineage/out/target/product/basic_x86_64_pc/ramdisk.img)" >> $GITHUB_ENV
          echo "RECOVERY=$(find android/lineage/out/target/product/basic_x86_64_pc/ramdisk-recovery.img)" >> $GITHUB_ENV

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            ${{ env.KERNEL }}
            ${{ env.SYSTEM }}
            ${{ env.RAMDISK }}
            ${{ env.RECOVERY }}
            ${{ env.VENDOR }}
